// Mocks generated by Mockito 5.4.6 from annotations
// in backend/test/services/emergency_process_sos_request_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:backend/repositories/emergency_repository.dart' as _i3;
import 'package:backend/repositories/user_repository.dart' as _i6;
import 'package:backend/services/notification_service.dart' as _i5;
import 'package:data_models/utente_generico.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUtenteGenerico_0 extends _i1.SmartFake
    implements _i2.UtenteGenerico {
  _FakeUtenteGenerico_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EmergencyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmergencyRepository extends _i1.Mock
    implements _i3.EmergencyRepository {
  @override
  _i4.Future<void> sendSos({
    required String? userId,
    required String? email,
    required String? phone,
    required String? type,
    required double? lat,
    required double? lng,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendSos, [], {
              #userId: userId,
              #email: email,
              #phone: phone,
              #type: type,
              #lat: lat,
              #lng: lng,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getAllActiveEmergencies() =>
      (super.noSuchMethod(
            Invocation.method(#getAllActiveEmergencies, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>?> getEmergencyByUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getEmergencyByUserId, [userId]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
            returnValueForMissingStub:
                _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<void> deleteSos(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSos, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateLocation(String? userId, double? lat, double? lng) =>
      (super.noSuchMethod(
            Invocation.method(#updateLocation, [userId, lat, lng]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i5.NotificationService {
  @override
  _i4.Future<void> sendBroadcast({
    required String? title,
    required String? body,
    required List<String>? tokens,
    String? type = 'emergency_alert',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendBroadcast, [], {
              #title: title,
              #body: body,
              #tokens: tokens,
              #type: type,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i6.UserRepository {
  @override
  _i4.Future<Map<String, dynamic>?> findUserByEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#findUserByEmail, [email]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
            returnValueForMissingStub:
                _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<Map<String, dynamic>?> findUserByPhone(String? phone) =>
      (super.noSuchMethod(
            Invocation.method(#findUserByPhone, [phone]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
            returnValueForMissingStub:
                _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<Map<String, dynamic>?> findUserById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#findUserById, [id]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
            returnValueForMissingStub:
                _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<_i2.UtenteGenerico> saveUser(_i2.UtenteGenerico? newUser) =>
      (super.noSuchMethod(
            Invocation.method(#saveUser, [newUser]),
            returnValue: _i4.Future<_i2.UtenteGenerico>.value(
              _FakeUtenteGenerico_0(
                this,
                Invocation.method(#saveUser, [newUser]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.UtenteGenerico>.value(
              _FakeUtenteGenerico_0(
                this,
                Invocation.method(#saveUser, [newUser]),
              ),
            ),
          )
          as _i4.Future<_i2.UtenteGenerico>);

  @override
  _i4.Future<Map<String, dynamic>> createUser(
    Map<String, dynamic>? userData, {
    String? collection = 'users',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createUser,
              [userData],
              {#collection: collection},
            ),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> updateUserGeneric(int? id, Map<String, dynamic>? updates) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserGeneric, [id, updates]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateUserField(int? id, String? fieldName, dynamic value) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserField, [id, fieldName, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> deleteUser(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [id]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> addToArrayField(int? id, String? fieldName, dynamic item) =>
      (super.noSuchMethod(
            Invocation.method(#addToArrayField, [id, fieldName, item]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeFromArrayField(
    int? id,
    String? fieldName,
    dynamic item,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromArrayField, [id, fieldName, item]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveOtp(String? telefono, String? otp) =>
      (super.noSuchMethod(
            Invocation.method(#saveOtp, [telefono, otp]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> verifyOtp(String? telefono, String? otp) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOtp, [telefono, otp]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> markUserAsVerified(String? identifier) =>
      (super.noSuchMethod(
            Invocation.method(#markUserAsVerified, [identifier]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<String>> getCitizenTokens({int? excludedId}) =>
      (super.noSuchMethod(
            Invocation.method(#getCitizenTokens, [], {#excludedId: excludedId}),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i4.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<List<String>> getRescuerTokens({int? excludedId}) =>
      (super.noSuchMethod(
            Invocation.method(#getRescuerTokens, [], {#excludedId: excludedId}),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i4.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i4.Future<List<String>>);
}
